// Generated by ReScript, PLEASE EDIT WITH CARE

import Gun from "gun";
import SeaJs from "gun/sea.js";
import UnsetJs from "gun/lib/unset.js";

var gunUrl = [
  "https://gun-manhattan.herokuapp.com/gun",
  "http://cashtokens.paper.cash:8765/gun"
];

var storesLabel = "stores";

var Constants = {
  gunUrl: gunUrl,
  storesLabel: storesLabel
};

var $$null = null;

var Types = {
  $$null: $$null
};

async function asyncWork(sea, string) {
  return await sea.work(string, $$null, $$null, {
              name: "SHA-256"
            });
}

var Sea = {
  asyncWork: asyncWork
};

var Gun$1 = {};

var gun = Gun({
      peers: gunUrl
    });

var sea = SeaJs;

async function registerStore(name, email) {
  var storeId = await asyncWork(sea, email);
  var storeRef = gun.get(storesLabel).get(storeId);
  await storeRef.put({
        name: name,
        email: email
      });
  return storeId;
}

async function enterQueue(customerName, storeId) {
  var storeRef = gun.get("stores").get(storeId);
  var store = await storeRef.once();
  console.log("store", store);
  var queue = await storeRef.get("queue").once();
  console.log("queue", queue);
  var queuePosition_timestamp = new Date().toISOString();
  var queuePosition = {
    customerName: customerName,
    position: 1,
    status: "waiting",
    timestamp: queuePosition_timestamp
  };
  console.log("queuePosition", queuePosition);
  await queue.set(queuePosition);
  var queueArr = queue.once();
  console.log("queueArr", queueArr);
  var queuePositionId = await asyncWork(sea, "" + customerName + ":" + queuePosition_timestamp + "");
  var queuePositionRef = gun.get("queuePositions").get(queuePositionId, (function (x) {
          console.log("queuePositionId", x);
        }));
  var queueD = await queuePositionRef.put(queuePosition);
  console.log("queueD", queueD);
  return queuePositionId;
}

async function unsetEverything(storeId) {
  var storeRef = gun.get("stores").get(storeId);
  return await gun.unset(storeRef);
}

async function main(param) {
  var storeId = await registerStore("My Store", "example@example.com");
  gun.get("stores").get(storeId).on(function (x) {
        console.log("storeRef", x);
      });
  console.log("Store ID: ", storeId);
  var queuePositionId = await enterQueue("John", storeId);
  console.log("User entered queue with position ID:", queuePositionId);
}

main(undefined);

export {
  Constants ,
  Types ,
  Sea ,
  Gun$1 as Gun,
  gun ,
  sea ,
  registerStore ,
  enterQueue ,
  unsetEverything ,
  main ,
}
/*  Not a pure module */
