// Generated by ReScript, PLEASE EDIT WITH CARE

import Gun from "gun/gun";
import Sea from "gun/sea";

var $$null = null;

var Types = {
  $$null: $$null
};

var gun = Gun();

var sea = Sea();

async function registerStore(name, email) {
  var storeId = await sea.work(email, $$null, $$null, {
        name: "SHA-256"
      });
  var storeRef = gun.get(storeId);
  return await storeRef.put({
              name: name,
              email: email
            });
}

export {
  Types ,
  gun ,
  sea ,
  registerStore ,
}
/* gun Not a pure module */
